image: node:carbon
pipelines:
  default:
    - step:
        name: Audit NPM vulnerabilities
        image:
          name: oltregistry.azurecr.io/tools/npm-audit-ci:latest
          username: $REGISTRY_USER
          password: $REGISTRY_PASSWORD
        script:
          - npm install
          - /app/bin/npm-audit-ci -m # Fail with moderate severity or higher
    - step:
        name: Run tests
        script:
          - npm install
          - npm run build
          - npm test
      caches:
        - node
  tags:
    '*':
      - step:
          name: Audit NPM vulnerabilities
          image:
            name: oltregistry.azurecr.io/tools/npm-audit-ci:latest
            username: $REGISTRY_USER
            password: $REGISTRY_PASSWORD
          script:
            - npm install
            - /app/bin/npm-audit-ci -m # Fail with moderate severity or higher
      - step:
          name: Run tests
          script:
            - npm install
            - npm test
      - step:
          name: Publish package on NPM
          script:
          - npm install
          - npm run build
          - npm version --no-git-tag-version $BITBUCKET_TAG
          - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN_PUBLISH}" > .npmrc
          - npm publish
        caches:
          - node