apiVersion: v1
kind: Service
metadata:
  name: styleguide
  labels:
    buildingBlock: {{ .Values.labels.buildingBlock }}
    component: {{ .Values.labels.component }}
  annotations: {}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-port
  selector:
    buildingBlock: {{ .Values.labels.buildingBlock }}
    component: {{ .Values.labels.component }}
